<?php

namespace Muneris\Bundle\MaxMindBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MaxMindCacheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaxMindCacheRepository extends EntityRepository
{
    public function findByIp($ip)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT i FROM MunerisMaxMindBundle:MaxMindCache i WHERE i.createdAt > :date AND i.ip = :ip')
            ->setParameter('date', date('Y-m-d H:i:s', strtotime('-1 WEEK')))
            ->setParameter('ip', $ip)
            ->getResult()
        ;
    }
}
