<?php

namespace Muneris\Bundle\GeoPostcodesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LocalGeoPostcodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocalGeoPostcodeRepository extends EntityRepository
{
    /**
     * FindByFuzzy tries to find cities based on either zip code or city name
     * The zip code is guessed from many formats, some are known, some are not.
     *
     * @param  String $country Iso 2 country code
     * @param  String $fuzzy   Search value
     *
     * @return mixed
     */
    public function findByFuzzy($country, $fuzzy)
    {
        $params[':country'] = $country;

        $qb = $this->createQueryBuilder('g')
            ->where('g.country = :country')
            ->groupBy('g.city')
        ;

        $fb = new FuzzyBuilder($qb, $country, $fuzzy);

        list($fb, $params) = $fb->fuzz($params);

        $result = $fb->setParameters($params)
            ->getQuery()
            ->getResult()
        ;

        if (count($result)) {
            return $result;
        }

        return null;
    }
}
